# Generated by Django 5.0.2 on 2025-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_short_description_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
