# Generated by Django 5.0.2 on 2025-01-29 16:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
