# Generated by Django 5.0.2 on 2025-01-29 16:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(),
        ),
    ]
