# Generated by Django 5.0.2 on 2025-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_blog_ckblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
    ]
