# Generated by Django 5.0.2 on 2025-01-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_ckblog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CKBlog',
        ),
    ]
